### ISSUE TITLE
Visualize individual dynamic risk trajectories

### ISSUE THREAD

**Issue by Jerryhe99** [thehanlab/dynamicLM#10]
Thank you for developing the dynamicLM package! I’ve been following the README file for landmark analysis, and both the model construction and AUC computations are working as expected.
However, when I try to visualize individual dynamic risk trajectories, I encounter the following error:

> "Error in sum(sapply(bet_covars, function(coef_name) { : 
>   invalid 'type' (list) of argument".

Could you please advise on how to resolve this issue? Any guidance on adjustments I should make would be greatly appreciated!

Below is an example of the code:
```
print(supermodel)

Landmark cox super model fit for dynamic prediction of window size 5:

$model
                      coef  exp(coef)   se(coef)  robust se      z      p
lgmap            9.646e+00  1.546e+04  3.492e-01  5.378e-01 17.936 <2e-16
height           -1.843e-01  8.317e-01  5.975e-01  5.814e-01 -0.317 0.7513
bmi             -1.430e+00  2.393e-01  9.036e-01  9.174e-01 -1.559 0.1191
matsmok          2.135e+01  1.876e+09  1.030e+01  9.162e+00  2.331 0.0198
prev_gestdiab   -2.539e+01  9.418e-12  1.112e+01  1.093e+01 -2.323 0.0202
prev_gesthyp     2.161e+01  2.423e+09  1.048e+01  1.054e+01  2.051 0.0403
age_over35      -2.999e+01  9.416e-14  2.060e+01  2.077e+01 -1.444 0.1487
par              4.431e+00  8.404e+01  6.529e+00  7.498e+00  0.591 0.5545
hyp              5.181e+00  1.779e+02  8.458e+00  8.863e+00  0.585 0.5588
diab             6.102e-01  1.841e+00  1.777e+01  1.438e+01  0.042 0.9661
height_1          4.139e-03  1.004e+00  3.862e-02  3.769e-02  0.110 0.9126
height_2          2.384e-07  1.000e+00  6.173e-04  6.034e-04  0.000 0.9997
bmi_1            8.587e-02  1.090e+00  5.780e-02  5.917e-02  1.451 0.1467
bmi_2           -1.272e-03  9.987e-01  9.160e-04  9.439e-04 -1.347 0.1779
matsmok_1       -1.293e+00  2.745e-01  6.774e-01  6.117e-01 -2.114 0.0346
matsmok_2        1.900e-02  1.019e+00  1.096e-02  1.002e-02  1.897 0.0579
prev_gestdiab_1  1.459e+00  4.302e+00  7.041e-01  6.899e-01  2.115 0.0344
prev_gestdiab_2 -2.165e-02  9.786e-01  1.107e-02  1.080e-02 -2.004 0.0450
prev_gesthyp_1  -1.313e+00  2.691e-01  6.702e-01  6.658e-01 -1.972 0.0486
prev_gesthyp_2   2.076e-02  1.021e+00  1.061e-02  1.044e-02  1.988 0.0468
age_over35_1     1.914e+00  6.778e+00  1.283e+00  1.283e+00  1.492 0.1358
age_over35_2    -2.975e-02  9.707e-01  1.987e-02  1.971e-02 -1.510 0.1311
par_1           -3.417e-01  7.106e-01  4.239e-01  4.816e-01 -0.710 0.4780
par_2            5.576e-03  1.006e+00  6.799e-03  7.650e-03  0.729 0.4660
hyp_1           -1.691e-01  8.444e-01  5.490e-01  5.711e-01 -0.296 0.7671
hyp_2            1.030e-03  1.001e+00  8.807e-03  9.102e-03  0.113 0.9099
diab_1           2.414e-02  1.024e+00  1.161e+00  9.572e-01  0.025 0.9799
diab_2          -2.107e-04  9.998e-01  1.872e-02  1.566e-02 -0.013 0.9893
LM_1            -1.442e+00  2.365e-01  6.732e+00  6.502e+00 -0.222 0.8245
LM_2             9.590e-03  1.010e+00  1.075e-01  1.037e-01  0.092 0.9263

Likelihood ratio test=1366  on 30 df, p=< 2.2e-16
n= 75320, number of events= 508 
   (1194 observations deleted due to missingness)
lmdatanew <- stack_data(data[idx,],outcome,lms,w,covs,format="long",id="ID",rtime="week")
lmdatanew<-add_interactions(lmdatanew,pred_covars,
+                            func_covars = c("linear","quadratic"),
+                            func_lms = c("linear","quadratic"))
inds<-lmdatanew$data  
plotrisk(supermodel, inds, format = "long", ylim = c(0, 0.2))
Error in sum(sapply(bet_covars, function(coef_name) { : 
  invalid 'type' (list) of argument

```

**Comment by anyafries** [comment]
Thanks for using the package!

We have just released a new version of the package which hopefully addresses this issue.

Could you reinstall the package (see the updated tutorial documentation) and rerun your code? This requires running:

```r
# install.packages("devtools")
devtools::install_github("tagteam/riskRegression")
devtools::install_github("thehanlab/dynamicLM")
```

**Please note that we have updated variable naming** so that `variable_1` will become `variable_LM1` (identical for the other variables) and `LM_1` becomes `LM1` (identical for the other landmark transformations). 

Please let me know if this works/not!

Links:
* [Original tutorial](https://github.com/thehanlab/dynamicLM/blob/main/tutorials/tutorial2-recurrence-data.md) (with updated code)
* [New tutorial](https://github.com/thehanlab/dynamicLM/tree/main?tab=readme-ov-file#1-dynamiclm)

**Comment by Jerryhe99** [comment]
Thank you for your prompt reply! I have reinstalled the package, but it doesn't seem to have resolved the issue, as I am still encountering the same problem.

**Comment by anyafries** [comment]
Thanks for trying that! 

I have tried but am unable to reproduce your error. Are you able to share code using the data in the package that creates the error or a minimal reproducible version of your code or share a .rda of `supermodel` and `inds`?

**Comment by Jerryhe99** [comment]
Thank you! Could you kindly provide an email address, or let me know if there is another preferred method for sending the data?

**Comment by anyafries** [comment]
anya [dot] fries [at] stanford [dot] edu

**Comment by anyafries** [comment]
The issue is that `plotrisk` requires `data` to be a data.frame and errors with a tibble.

The following code is error free:
```r
plotrisk(supermodel, as.data.frame(inds), format = "long", ylim = c(0, 0.2))
```

A further argument check has been added to `plotrisk` to avoid this behaviour in the future.

**Comment by Jerryhe99** [comment]
Thank you for your patient explanation. My problem has been perfectly solved!
